import './sass/main.scss';
import './js/renderHeaderHomeStart';
import './js/renderNews';
import './js/getPopularFilms';
import './js/localStorage';
import './js/annoying';
import './js/spinnerExample';
import './js/scrollOnTop';
import './js/modal';
